"""Added direction_id column to account

Revision ID: bb2f24745a30
Revises: c74686773021
Create Date: 2024-12-08 20:47:50.079862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2f24745a30'
down_revision = 'c74686773021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('direction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
